-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 10:54:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema STMVendorer_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `STMVendorer_db` ;

-- -----------------------------------------------------
-- Schema STMVendorer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `STMVendorer_db` DEFAULT CHARACTER SET utf8 ;
USE `STMVendorer_db` ;

-- -----------------------------------------------------
-- Table `STMVendorer_db`.`fundacje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`fundacje` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`fundacje` (
  `pk` BIGINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `nazwa` VARCHAR(255) NOT NULL,
  `nip` CHAR(10) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `regon` VARCHAR(14) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` VARCHAR(20) NOT NULL,
  UNIQUE INDEX (`email` ASC),
  UNIQUE INDEX (`nazwa` ASC),
  UNIQUE INDEX (`nip` ASC),
  UNIQUE INDEX (`regon` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`start_upy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`start_upy` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`start_upy` (
  `pk` BIGINT NOT NULL,
  `nazwa` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `nip` CHAR(10) NULL DEFAULT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `regon` VARCHAR(14) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` VARCHAR(20) NOT NULL,
  UNIQUE INDEX (`nazwa` ASC),
  UNIQUE INDEX (`email` ASC),
  UNIQUE INDEX (`nip` ASC),
  UNIQUE INDEX (`regon` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`datki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`datki` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`datki` (
  `pk` BIGINT NOT NULL,
  `fk_fundacja` INT NULL DEFAULT NULL,
  `fk_start_up` INT NULL DEFAULT NULL,
  `forma` TINYINT NOT NULL,
  `kwota` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fundacje_datki` (`fk_fundacja` ASC),
  INDEX `start_upy_datki` (`fk_start_up` ASC),
  CONSTRAINT `fundacje_datki`
    FOREIGN KEY (`fk_fundacja`)
    REFERENCES `STMVendorer_db`.`fundacje` (`pk`),
  CONSTRAINT `start_upy_datki`
    FOREIGN KEY (`fk_start_up`)
    REFERENCES `STMVendorer_db`.`start_upy` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`towary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`towary` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`towary` (
  `pk` BIGINT NOT NULL,
  `nazwa` VARCHAR(255) NOT NULL,
  `kod_producenta` VARCHAR(10) NOT NULL,
  `opis` VARCHAR(1000) NOT NULL,
  `dostępność` TINYINT NOT NULL,
  `cena_jedn_netto` DECIMAL(19,2) NOT NULL,
  `cena_jedn_brutto` DECIMAL(19,2) NOT NULL,
  `stawka_vat` DECIMAL(3,2) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`towary_datki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`towary_datki` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`towary_datki` (
  `pk` BIGINT NOT NULL,
  `fk_datki` INT NOT NULL,
  `fk_towary` INT NOT NULL,
  `ilość` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `FKtowary_dat174827` (`fk_datki` ASC),
  INDEX `towary_datki` (`fk_towary` ASC),
  CONSTRAINT `FKtowary_dat174827`
    FOREIGN KEY (`fk_datki`)
    REFERENCES `STMVendorer_db`.`datki` (`pk`),
  CONSTRAINT `towary_datki`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `STMVendorer_db`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`płatności`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`płatności` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`płatności` (
  `pk` BIGINT NOT NULL,
  `rodzaj_płatności` VARCHAR(255) NOT NULL,
  UNIQUE INDEX (`rodzaj_płatności` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`dane_przedsiębiorstw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`dane_przedsiębiorstw` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`dane_przedsiębiorstw` (
  `pk` BIGINT NOT NULL,
  `województwo` VARCHAR(20) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `nazwa_przedsiębiorstwa` VARCHAR(255) NOT NULL,
  `nip` CHAR(10) NOT NULL,
  `regon` VARCHAR(14) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  UNIQUE INDEX (`nazwa_przedsiębiorstwa` ASC),
  UNIQUE INDEX (`nip` ASC),
  UNIQUE INDEX (`regon` ASC),
  UNIQUE INDEX (`email` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`punkty_sprzedaży`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`punkty_sprzedaży` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`punkty_sprzedaży` (
  `pk` BIGINT NOT NULL,
  `fk_dane_przedsiębiorstw` INT NOT NULL,
  `województwo` VARCHAR(20) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `dane_przedsiębiorstw_punkty_sprzedaży` (`fk_dane_przedsiębiorstw` ASC),
  CONSTRAINT `dane_przedsiębiorstw_punkty_sprzedaży`
    FOREIGN KEY (`fk_dane_przedsiębiorstw`)
    REFERENCES `STMVendorer_db`.`dane_przedsiębiorstw` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`sprzedaże`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`sprzedaże` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`sprzedaże` (
  `pk` BIGINT NOT NULL,
  `fk_płatności` INT NOT NULL,
  `fk_punkt_sprzedaży` INT NOT NULL,
  `data_zlecenia_sprzedaży` TIMESTAMP NOT NULL,
  `data_zaksięgowania_płatności` TIMESTAMP NOT NULL,
  `cena_sum_netto` DECIMAL(19,2) NOT NULL,
  `cena_sum_brutto` DECIMAL(19,2) NOT NULL,
  `rabat` DECIMAL(1,2) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `płatności_sprzedaże` (`fk_płatności` ASC),
  INDEX `punkty_sprzedaży_sprzedaże` (`fk_punkt_sprzedaży` ASC),
  CONSTRAINT `płatności_sprzedaże`
    FOREIGN KEY (`fk_płatności`)
    REFERENCES `STMVendorer_db`.`płatności` (`pk`),
  CONSTRAINT `punkty_sprzedaży_sprzedaże`
    FOREIGN KEY (`fk_punkt_sprzedaży`)
    REFERENCES `STMVendorer_db`.`punkty_sprzedaży` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`towary_sprzedaże`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`towary_sprzedaże` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`towary_sprzedaże` (
  `pk` BIGINT NOT NULL,
  `fk_towary` INT NOT NULL,
  `fk_sprzedaże` INT NOT NULL,
  `ilość` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `towary_towary_sprzedaże` (`fk_towary` ASC),
  INDEX `FKtowary_spr256522` (`fk_sprzedaże` ASC),
  CONSTRAINT `towary_towary_sprzedaże`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `STMVendorer_db`.`towary` (`pk`),
  CONSTRAINT `FKtowary_spr256522`
    FOREIGN KEY (`fk_sprzedaże`)
    REFERENCES `STMVendorer_db`.`sprzedaże` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`hurtownie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`hurtownie` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`hurtownie` (
  `pk` BIGINT NOT NULL,
  `kod_hurtowni` CHAR(6) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` VARCHAR(20) NOT NULL,
  `status` TINYINT NOT NULL,
  UNIQUE INDEX (`kod_hurtowni` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`stany_magazynowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`stany_magazynowe` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`stany_magazynowe` (
  `pk` BIGINT NOT NULL,
  `fk_hurtownie` INT NOT NULL,
  `fk_towary` INT NOT NULL,
  `ilość` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `hurtownie_towary_stany_magazynowe` (`fk_hurtownie` ASC),
  INDEX `towary_stany_magazynowe` (`fk_towary` ASC),
  CONSTRAINT `hurtownie_towary_stany_magazynowe`
    FOREIGN KEY (`fk_hurtownie`)
    REFERENCES `STMVendorer_db`.`hurtownie` (`pk`),
  CONSTRAINT `towary_stany_magazynowe`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `STMVendorer_db`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`dostawcy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`dostawcy` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`dostawcy` (
  `pk` BIGINT NOT NULL,
  `nazwa` VARCHAR(255) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `hashowane_haslo` VARCHAR(64) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `nip` CHAR(10) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` VARCHAR(20) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  UNIQUE INDEX (`nip` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`stanowiska`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`stanowiska` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`stanowiska` (
  `pk` BIGINT NOT NULL,
  `nazwa` VARCHAR(20) NOT NULL,
  UNIQUE INDEX (`nazwa` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`umowy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`umowy` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`umowy` (
  `pk` BIGINT NOT NULL,
  `rodzaj` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`pracownicy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`pracownicy` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`pracownicy` (
  `pk` BIGINT NOT NULL,
  `fk_stanowiska` INT NULL DEFAULT NULL,
  `fk_umowy` INT NOT NULL,
  `fk_hurtownie` INT NOT NULL,
  `imię` VARCHAR(50) NOT NULL,
  `nazwisko` VARCHAR(50) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `pesel` CHAR(11) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `nip` CHAR(10) NULL DEFAULT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `drugie_imię` VARCHAR(50) NOT NULL,
  `nazwa_użytkownika` VARCHAR(50) NOT NULL,
  `hashowane_hasło` VARCHAR(64) NOT NULL,
  `zatrudnienie` TINYINT NULL DEFAULT NULL,
  UNIQUE INDEX (`fk_umowy` ASC),
  UNIQUE INDEX (`pesel` ASC),
  UNIQUE INDEX (`nip` ASC),
  UNIQUE INDEX (`numer_telefonu` ASC),
  PRIMARY KEY (`pk`),
  INDEX `stanowiska_pracownicy` (`fk_stanowiska` ASC),
  INDEX `hurtownie_pracownicy` (`fk_hurtownie` ASC),
  CONSTRAINT `stanowiska_pracownicy`
    FOREIGN KEY (`fk_stanowiska`)
    REFERENCES `STMVendorer_db`.`stanowiska` (`pk`),
  CONSTRAINT `pracownicy_umowy`
    FOREIGN KEY (`fk_umowy`)
    REFERENCES `STMVendorer_db`.`umowy` (`pk`),
  CONSTRAINT `hurtownie_pracownicy`
    FOREIGN KEY (`fk_hurtownie`)
    REFERENCES `STMVendorer_db`.`hurtownie` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`zamówienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`zamówienia` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`zamówienia` (
  `pk` BIGINT NOT NULL,
  `fk_hurtownie` INT NOT NULL,
  `fk_dostawcy` INT NOT NULL,
  `fk_pracownicy` INT NOT NULL,
  `data_zlecenia` TIMESTAMP NOT NULL,
  `data_odbioru` TIMESTAMP NOT NULL,
  `cena_sum_netto` DECIMAL(19,2) NOT NULL,
  `cena_sum_brutto` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `hurtownie_zamówienia` (`fk_hurtownie` ASC),
  INDEX `dostawcy_zamówienia` (`fk_dostawcy` ASC),
  INDEX `pracownicy_zamówienia` (`fk_pracownicy` ASC),
  CONSTRAINT `hurtownie_zamówienia`
    FOREIGN KEY (`fk_hurtownie`)
    REFERENCES `STMVendorer_db`.`hurtownie` (`pk`),
  CONSTRAINT `dostawcy_zamówienia`
    FOREIGN KEY (`fk_dostawcy`)
    REFERENCES `STMVendorer_db`.`dostawcy` (`pk`),
  CONSTRAINT `pracownicy_zamówienia`
    FOREIGN KEY (`fk_pracownicy`)
    REFERENCES `STMVendorer_db`.`pracownicy` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`zamówienia_towary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`zamówienia_towary` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`zamówienia_towary` (
  `pk` BIGINT NOT NULL,
  `fk_zamówienia` INT NOT NULL,
  `fk_towary` INT NOT NULL,
  `cena_jedn_netto` DECIMAL(19,2) NOT NULL,
  `cena_jedn_brutto` DECIMAL(19,2) NOT NULL,
  `ilość` INT NOT NULL,
  `towarypk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `zamówienia_towary_sprzedaże` (`fk_zamówienia` ASC),
  INDEX `zamówienia_towary_towary` (`towarypk` ASC),
  CONSTRAINT `zamówienia_towary_sprzedaże`
    FOREIGN KEY (`fk_zamówienia`)
    REFERENCES `STMVendorer_db`.`zamówienia` (`pk`),
  CONSTRAINT `zamówienia_towary_towary`
    FOREIGN KEY (`towarypk`)
    REFERENCES `STMVendorer_db`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`uprawnienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`uprawnienia` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`uprawnienia` (
  `pk` BIGINT NOT NULL,
  `rodzaj` VARCHAR(100) NOT NULL,
  UNIQUE INDEX (`rodzaj` ASC),
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`stanowiska_uprawnienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`stanowiska_uprawnienia` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`stanowiska_uprawnienia` (
  `pk` BIGINT NOT NULL,
  `fk_stanowiska` INT NOT NULL,
  `fk_uprawnienia` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `stanowiska_stanowiska_uprawnienia` (`fk_stanowiska` ASC),
  INDEX `uprawnienia_stanowiska_uprawnienia` (`fk_uprawnienia` ASC),
  CONSTRAINT `stanowiska_stanowiska_uprawnienia`
    FOREIGN KEY (`fk_stanowiska`)
    REFERENCES `STMVendorer_db`.`stanowiska` (`pk`),
  CONSTRAINT `uprawnienia_stanowiska_uprawnienia`
    FOREIGN KEY (`fk_uprawnienia`)
    REFERENCES `STMVendorer_db`.`uprawnienia` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`przesunięcia_magazynowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`przesunięcia_magazynowe` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`przesunięcia_magazynowe` (
  `pk` BIGINT NOT NULL,
  `fk_hurtownia_źródłowa` INT NOT NULL,
  `fk_hurtownia_docelowa` INT NOT NULL,
  `fk_pracownik` INT NOT NULL,
  `data_zlecenia` TIMESTAMP NOT NULL,
  `data_realizacji` TIMESTAMP NOT NULL,
  `data_odbioru_końcowego` TIMESTAMP NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `hurtownie_przesunięcie_magazynowe_d` (`fk_hurtownia_źródłowa` ASC),
  INDEX `hurtownie_przesunięcie_magazynowe_ź` (`fk_hurtownia_docelowa` ASC),
  INDEX `prawcownicy_przesunięcia_magazynowe` (`fk_pracownik` ASC),
  CONSTRAINT `hurtownie_przesunięcie_magazynowe_d`
    FOREIGN KEY (`fk_hurtownia_źródłowa`)
    REFERENCES `STMVendorer_db`.`hurtownie` (`pk`),
  CONSTRAINT `hurtownie_przesunięcie_magazynowe_ź`
    FOREIGN KEY (`fk_hurtownia_docelowa`)
    REFERENCES `STMVendorer_db`.`hurtownie` (`pk`),
  CONSTRAINT `prawcownicy_przesunięcia_magazynowe`
    FOREIGN KEY (`fk_pracownik`)
    REFERENCES `STMVendorer_db`.`pracownicy` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`towary_przesunięcia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`towary_przesunięcia` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`towary_przesunięcia` (
  `pk` BIGINT NOT NULL,
  `fk_przesunięcia_magazynowe` INT NOT NULL,
  `fk_towary` INT NOT NULL,
  `ilość` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `przesunięcia_magazynowe_towary_przesunięcia` (`fk_przesunięcia_magazynowe` ASC),
  INDEX `towary_towary_przesunięcia` (`fk_towary` ASC),
  CONSTRAINT `przesunięcia_magazynowe_towary_przesunięcia`
    FOREIGN KEY (`fk_przesunięcia_magazynowe`)
    REFERENCES `STMVendorer_db`.`przesunięcia_magazynowe` (`pk`),
  CONSTRAINT `towary_towary_przesunięcia`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `STMVendorer_db`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`faktury`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`faktury` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`faktury` (
  `pk` BIGINT NOT NULL,
  `fk_pracownik` INT NOT NULL,
  `fk_sprzedaż` INT NOT NULL,
  `imię_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `nazwisko_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `numer_telefonu_nabywcy` VARCHAR(11) NULL DEFAULT NULL,
  `email_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `stawka_vat` DECIMAL(3,2) NOT NULL,
  `data_wystawienia` TIMESTAMP NOT NULL,
  `fk_dane_przedsiębiorstw` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `pracownicy_faktury` (`fk_pracownik` ASC),
  INDEX `sprzedaże_faktury` (`fk_sprzedaż` ASC),
  INDEX `dane_przedsiębiorstw` (`fk_dane_przedsiębiorstw` ASC),
  CONSTRAINT `pracownicy_faktury`
    FOREIGN KEY (`fk_pracownik`)
    REFERENCES `STMVendorer_db`.`pracownicy` (`pk`),
  CONSTRAINT `sprzedaże_faktury`
    FOREIGN KEY (`fk_sprzedaż`)
    REFERENCES `STMVendorer_db`.`sprzedaże` (`pk`),
  CONSTRAINT `dane_przedsiębiorstw`
    FOREIGN KEY (`fk_dane_przedsiębiorstw`)
    REFERENCES `STMVendorer_db`.`dane_przedsiębiorstw` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`listy_przewozowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`listy_przewozowe` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`listy_przewozowe` (
  `pk` BIGINT NOT NULL,
  `fk_sprzedaż` INT NULL DEFAULT NULL,
  `fk_dostawca` INT NOT NULL,
  `fk_przesunięcie_magazynowe` INT NULL DEFAULT NULL,
  `data_wystawienia` TIMESTAMP NOT NULL,
  `data_przyjęcia_do_przewozu` TIMESTAMP NOT NULL,
  `sposób_pakowania` VARCHAR(255) NOT NULL,
  `waga` DECIMAL(10,3) NOT NULL,
  `rodzaj_towaru` VARCHAR(255) NOT NULL,
  `koszt_wysyłki_netto` DECIMAL(19,2) NOT NULL,
  `koszt_wysyłki_brutto` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `sprzedaże_listy_przewozowe` (`fk_sprzedaż` ASC),
  INDEX `dostawcy_faktury` (`fk_dostawca` ASC),
  INDEX `przesunięcia_magazynowe_listy_przewozowe` (`fk_przesunięcie_magazynowe` ASC),
  CONSTRAINT `sprzedaże_listy_przewozowe`
    FOREIGN KEY (`fk_sprzedaż`)
    REFERENCES `STMVendorer_db`.`sprzedaże` (`pk`),
  CONSTRAINT `dostawcy_faktury`
    FOREIGN KEY (`fk_dostawca`)
    REFERENCES `STMVendorer_db`.`dostawcy` (`pk`),
  CONSTRAINT `przesunięcia_magazynowe_listy_przewozowe`
    FOREIGN KEY (`fk_przesunięcie_magazynowe`)
    REFERENCES `STMVendorer_db`.`przesunięcia_magazynowe` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`kategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`kategorie` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`kategorie` (
  `pk` BIGINT NOT NULL,
  `kategoria` VARCHAR(30) NOT NULL,
  `id_pokategorii` INT NULL DEFAULT NULL,
  UNIQUE INDEX (`kategoria` ASC),
  UNIQUE INDEX (`id_pokategorii` ASC),
  PRIMARY KEY (`pk`),
  CONSTRAINT `kategorie_kategorie`
    FOREIGN KEY (`id_pokategorii`)
    REFERENCES `STMVendorer_db`.`kategorie` (`pk`));


-- -----------------------------------------------------
-- Table `STMVendorer_db`.`towary_kategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STMVendorer_db`.`towary_kategorie` ;

CREATE TABLE IF NOT EXISTS `STMVendorer_db`.`towary_kategorie` (
  `pk` BIGINT NOT NULL,
  `id_towary` INT NOT NULL,
  `id_kategorie_towaru` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `towary_towary_kategorie` (`id_towary` ASC),
  INDEX `kategorie_towary_kategorie` (`id_kategorie_towaru` ASC),
  CONSTRAINT `towary_towary_kategorie`
    FOREIGN KEY (`id_towary`)
    REFERENCES `STMVendorer_db`.`towary` (`pk`),
  CONSTRAINT `kategorie_towary_kategorie`
    FOREIGN KEY (`id_kategorie_towaru`)
    REFERENCES `STMVendorer_db`.`kategorie` (`pk`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
