-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 13:20:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dane_przedsiębiorstw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dane_przedsiębiorstw` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `województwo` CHAR(2) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `nazwa_przedsiębiorstwa` VARCHAR(255) NOT NULL,
  `nip` CHAR(10) NOT NULL,
  `regon` VARCHAR(14) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  UNIQUE INDEX (`nazwa_przedsiębiorstwa` ASC) VISIBLE,
  UNIQUE INDEX (`nip` ASC) VISIBLE,
  UNIQUE INDEX (`regon` ASC) VISIBLE,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`fundacje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fundacje` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `nazwa` VARCHAR(255) NOT NULL,
  `nip` CHAR(10) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `regon` VARCHAR(14) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` CHAR(2) NOT NULL,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  UNIQUE INDEX (`nazwa` ASC) VISIBLE,
  UNIQUE INDEX (`nip` ASC) VISIBLE,
  UNIQUE INDEX (`regon` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`start_upy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`start_upy` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `nip` CHAR(10) NULL DEFAULT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `regon` VARCHAR(14) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` CHAR(2) NOT NULL,
  UNIQUE INDEX (`nazwa` ASC) VISIBLE,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  UNIQUE INDEX (`nip` ASC) VISIBLE,
  UNIQUE INDEX (`regon` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`datki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datki` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `fk_fundacja` INT(10) NULL DEFAULT NULL,
  `fk_start_up` INT(10) NULL DEFAULT NULL,
  `forma` TINYINT(1) NOT NULL,
  `kwota` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fundacje_datki` (`fk_fundacja` ASC) VISIBLE,
  INDEX `start_upy_datki` (`fk_start_up` ASC) VISIBLE,
  CONSTRAINT `fundacje_datki`
    FOREIGN KEY (`fk_fundacja`)
    REFERENCES `mydb`.`fundacje` (`pk`),
  CONSTRAINT `start_upy_datki`
    FOREIGN KEY (`fk_start_up`)
    REFERENCES `mydb`.`start_upy` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`dostawcy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dostawcy` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `hashowane_haslo` VARCHAR(64) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `nip` CHAR(10) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` CHAR(2) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  UNIQUE INDEX (`nip` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`hurtownie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hurtownie` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `kod_hurtowni` CHAR(6) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `województwo` CHAR(2) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  UNIQUE INDEX (`kod_hurtowni` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`umowy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`umowy` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(20) NOT NULL,
  `dokument` BLOB NOT NULL,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`stanowiska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stanowiska` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(20) NOT NULL,
  UNIQUE INDEX (`nazwa` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pracownicy` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_stanowiska` INT(11) NULL DEFAULT NULL,
  `fk_umowy` INT(11) NOT NULL,
  `fk_hurtownie` INT(10) NOT NULL,
  `imię` VARCHAR(50) NOT NULL,
  `nazwisko` VARCHAR(50) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `pesel` CHAR(11) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `nip` CHAR(10) NULL DEFAULT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `drugie_imię` VARCHAR(50) NOT NULL,
  `nazwa_użytkownika` VARCHAR(50) NOT NULL,
  `hashowane_hasło` VARCHAR(64) NOT NULL,
  `zatrudnienie` TINYINT(1) NULL DEFAULT NULL,
  UNIQUE INDEX (`fk_umowy` ASC) VISIBLE,
  UNIQUE INDEX (`pesel` ASC) VISIBLE,
  UNIQUE INDEX (`nip` ASC) VISIBLE,
  UNIQUE INDEX (`numer_telefonu` ASC) VISIBLE,
  PRIMARY KEY (`pk`),
  INDEX `hurtownie_pracownicy` (`fk_hurtownie` ASC) VISIBLE,
  INDEX `stanowiska_pracownicy` (`fk_stanowiska` ASC) VISIBLE,
  CONSTRAINT `hurtownie_pracownicy`
    FOREIGN KEY (`fk_hurtownie`)
    REFERENCES `mydb`.`hurtownie` (`pk`),
  CONSTRAINT `pracownicy_umowy`
    FOREIGN KEY (`fk_umowy`)
    REFERENCES `mydb`.`umowy` (`pk`),
  CONSTRAINT `stanowiska_pracownicy`
    FOREIGN KEY (`fk_stanowiska`)
    REFERENCES `mydb`.`stanowiska` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`punkty_sprzedaży`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`punkty_sprzedaży` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `fk_dane_przedsiębiorstw` INT(10) NOT NULL,
  `województwo` CHAR(2) NOT NULL,
  `powiat` CHAR(4) NOT NULL,
  `gmina` CHAR(6) NOT NULL,
  `kod_pocztowy` CHAR(6) NOT NULL,
  `miejscowość` VARCHAR(35) NOT NULL,
  `ulica` VARCHAR(80) NOT NULL,
  `numer_mieszkania` VARCHAR(6) NOT NULL,
  `numer_telefonu` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `dane_przedsiębiorstw_punkty_sprzedaży` (`fk_dane_przedsiębiorstw` ASC) VISIBLE,
  CONSTRAINT `dane_przedsiębiorstw_punkty_sprzedaży`
    FOREIGN KEY (`fk_dane_przedsiębiorstw`)
    REFERENCES `mydb`.`dane_przedsiębiorstw` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`płatności`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`płatności` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `rodzaj_płatności` VARCHAR(255) NOT NULL,
  UNIQUE INDEX (`rodzaj_płatności` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`sprzedaże`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sprzedaże` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_płatności` INT(11) NOT NULL,
  `fk_punkt_sprzedaży` INT(10) NOT NULL,
  `data_zlecenia_sprzedaży` TIMESTAMP NOT NULL,
  `data _zaksięgowania_płatności` TIMESTAMP NULL DEFAULT NULL,
  `cena_sum_netto` DECIMAL(19,2) NOT NULL,
  `cena_sum_brutto` DECIMAL(19,2) NOT NULL,
  `rabat` DECIMAL(1,2) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `punkty_sprzedaży_sprzedaże` (`fk_punkt_sprzedaży` ASC) VISIBLE,
  INDEX `płatności_sprzedaże` (`fk_płatności` ASC) VISIBLE,
  CONSTRAINT `punkty_sprzedaży_sprzedaże`
    FOREIGN KEY (`fk_punkt_sprzedaży`)
    REFERENCES `mydb`.`punkty_sprzedaży` (`pk`),
  CONSTRAINT `płatności_sprzedaże`
    FOREIGN KEY (`fk_płatności`)
    REFERENCES `mydb`.`płatności` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`faktury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faktury` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_pracownik` INT(11) NOT NULL,
  `fk_sprzedaż` INT(11) NOT NULL,
  `imię_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `nazwisko_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `nazwa_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `ulica_nabywcy` VARCHAR(80) NOT NULL,
  `numer_mieszkania_nabywcy` VARCHAR(6) NOT NULL,
  `kod_pocztowy_nabywcy` CHAR(6) NOT NULL,
  `miejscowość_nabywcy` VARCHAR(35) NOT NULL,
  `numer_telefonu_nabywcy` VARCHAR(11) NULL DEFAULT NULL,
  `email_nabywcy` VARCHAR(255) NULL DEFAULT NULL,
  `stawka_vat` CHAR(2) NOT NULL,
  `data_wystawienia` TIMESTAMP NOT NULL,
  `nip` CHAR(10) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `pracownicy_faktury` (`fk_pracownik` ASC) VISIBLE,
  INDEX `sprzedaże_faktury` (`fk_sprzedaż` ASC) VISIBLE,
  CONSTRAINT `pracownicy_faktury`
    FOREIGN KEY (`fk_pracownik`)
    REFERENCES `mydb`.`pracownicy` (`pk`),
  CONSTRAINT `sprzedaże_faktury`
    FOREIGN KEY (`fk_sprzedaż`)
    REFERENCES `mydb`.`sprzedaże` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kategorie` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `kategoria` VARCHAR(30) NOT NULL,
  `id_pokategorii` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX (`kategoria` ASC) VISIBLE,
  UNIQUE INDEX (`id_pokategorii` ASC) VISIBLE,
  PRIMARY KEY (`pk`),
  CONSTRAINT `kategorie_kategorie`
    FOREIGN KEY (`id_pokategorii`)
    REFERENCES `mydb`.`kategorie` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`przesunięcia_magazynowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`przesunięcia_magazynowe` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_hurtownia_źródłowa` INT(10) NOT NULL,
  `fk_hurtownia_docelowa` INT(10) NOT NULL,
  `fk_pracownik` INT(11) NOT NULL,
  `data_zlecenia` TIMESTAMP NOT NULL,
  `data_realizacji` TIMESTAMP NULL DEFAULT NULL,
  `data_odbioru_końcowego` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  INDEX `hurtownie_przesunięcie_magazynowe_1` (`fk_hurtownia_docelowa` ASC) VISIBLE,
  INDEX `hurtownie_przesunięcie_magazynowe_2` (`fk_hurtownia_źródłowa` ASC) VISIBLE,
  INDEX `prawcownicy_przesunięcia_magazynowe` (`fk_pracownik` ASC) VISIBLE,
  CONSTRAINT `hurtownie_przesunięcie_magazynowe_1`
    FOREIGN KEY (`fk_hurtownia_docelowa`)
    REFERENCES `mydb`.`hurtownie` (`pk`),
  CONSTRAINT `hurtownie_przesunięcie_magazynowe_2`
    FOREIGN KEY (`fk_hurtownia_źródłowa`)
    REFERENCES `mydb`.`hurtownie` (`pk`),
  CONSTRAINT `prawcownicy_przesunięcia_magazynowe`
    FOREIGN KEY (`fk_pracownik`)
    REFERENCES `mydb`.`pracownicy` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`listy_przewozowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listy_przewozowe` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_sprzedaż` INT(11) NOT NULL,
  `fk_dostawca` INT(10) NOT NULL,
  `fk_przesunięcie_magazynowe` INT(11) NULL DEFAULT NULL,
  `województwo_odbiorcy` CHAR(2) NOT NULL,
  `powiat_odbiorcy` CHAR(4) NOT NULL,
  `gmina_odbiorcy` CHAR(6) NOT NULL,
  `miejscowość_odbiorcy` VARCHAR(35) NOT NULL,
  `ulica_odbiorcy` VARCHAR(80) NOT NULL,
  `numer_mieszkania_odbiorcy` VARCHAR(6) NOT NULL,
  `kod_pocztowy_odbiorcy` CHAR(6) NOT NULL,
  `data_wystawienia` TIMESTAMP NOT NULL,
  `data_przyjęcia_do_przewozu` TIMESTAMP NULL DEFAULT NULL,
  `sposób_pakowania` VARCHAR(255) NOT NULL,
  `waga` DECIMAL(10,3) NOT NULL,
  `rodzaj_towaru` VARCHAR(255) NOT NULL,
  `koszt_wysyłki_netto` DECIMAL(19,2) NOT NULL,
  `koszt_wysyłki_brutto` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `dostawcy_faktury` (`fk_dostawca` ASC) VISIBLE,
  INDEX `przesunięcia_magazynowe_listy_przewozowe` (`fk_przesunięcie_magazynowe` ASC) VISIBLE,
  INDEX `sprzedaże_listy_przewozowe` (`fk_sprzedaż` ASC) VISIBLE,
  CONSTRAINT `dostawcy_faktury`
    FOREIGN KEY (`fk_dostawca`)
    REFERENCES `mydb`.`dostawcy` (`pk`),
  CONSTRAINT `przesunięcia_magazynowe_listy_przewozowe`
    FOREIGN KEY (`fk_przesunięcie_magazynowe`)
    REFERENCES `mydb`.`przesunięcia_magazynowe` (`pk`),
  CONSTRAINT `sprzedaże_listy_przewozowe`
    FOREIGN KEY (`fk_sprzedaż`)
    REFERENCES `mydb`.`sprzedaże` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`uprawnienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uprawnienia` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(100) NOT NULL,
  UNIQUE INDEX (`rodzaj` ASC) VISIBLE,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`stanowiska_uprawnienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stanowiska_uprawnienia` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_stanowiska` INT(11) NOT NULL,
  `fk_uprawnienia` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `stanowiska_stanowiska_uprawnienia` (`fk_stanowiska` ASC) VISIBLE,
  INDEX `uprawnienia_stanowiska_uprawnienia` (`fk_uprawnienia` ASC) VISIBLE,
  CONSTRAINT `stanowiska_stanowiska_uprawnienia`
    FOREIGN KEY (`fk_stanowiska`)
    REFERENCES `mydb`.`stanowiska` (`pk`),
  CONSTRAINT `uprawnienia_stanowiska_uprawnienia`
    FOREIGN KEY (`fk_uprawnienia`)
    REFERENCES `mydb`.`uprawnienia` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`towary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`towary` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL,
  `kod_producenta` VARCHAR(10) NOT NULL,
  `opis` VARCHAR(1000) NOT NULL,
  `dostępność` TINYINT(1) NOT NULL,
  `cena_jedn_netto` DECIMAL(19,2) NOT NULL,
  `cena_jedn_brutto` DECIMAL(19,2) NOT NULL,
  `stawka_vat` DECIMAL(1,2) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`stany_magazynowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stany_magazynowe` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_hurtownie` INT(10) NOT NULL,
  `fk_towary` INT(10) NOT NULL,
  `ilość` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `hurtownie_towary_stany_magazynowe` (`fk_hurtownie` ASC) VISIBLE,
  INDEX `towary_stany_magazynowe` (`fk_towary` ASC) VISIBLE,
  CONSTRAINT `hurtownie_towary_stany_magazynowe`
    FOREIGN KEY (`fk_hurtownie`)
    REFERENCES `mydb`.`hurtownie` (`pk`),
  CONSTRAINT `towary_stany_magazynowe`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `mydb`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`towary_datki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`towary_datki` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_datki` INT(10) NOT NULL,
  `fk_towary` INT(10) NOT NULL,
  `ilość` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `FKtowary_dat174827` (`fk_datki` ASC) VISIBLE,
  INDEX `towary_datki` (`fk_towary` ASC) VISIBLE,
  CONSTRAINT `FKtowary_dat174827`
    FOREIGN KEY (`fk_datki`)
    REFERENCES `mydb`.`datki` (`pk`),
  CONSTRAINT `towary_datki`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `mydb`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`towary_kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`towary_kategorie` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `id_towary` INT(10) NOT NULL,
  `id_kategorie_towaru` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `kategorie_towary_kategorie` (`id_kategorie_towaru` ASC) VISIBLE,
  INDEX `towary_towary_kategorie` (`id_towary` ASC) VISIBLE,
  CONSTRAINT `kategorie_towary_kategorie`
    FOREIGN KEY (`id_kategorie_towaru`)
    REFERENCES `mydb`.`kategorie` (`pk`),
  CONSTRAINT `towary_towary_kategorie`
    FOREIGN KEY (`id_towary`)
    REFERENCES `mydb`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`towary_przesunięcia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`towary_przesunięcia` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_przesunięcia_magazynowe` INT(11) NOT NULL,
  `fk_towary` INT(10) NOT NULL,
  `ilość` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `przesunięcia_magazynowe_towary_przesunięcia` (`fk_przesunięcia_magazynowe` ASC) VISIBLE,
  INDEX `towary_towary_przesunięcia` (`fk_towary` ASC) VISIBLE,
  CONSTRAINT `przesunięcia_magazynowe_towary_przesunięcia`
    FOREIGN KEY (`fk_przesunięcia_magazynowe`)
    REFERENCES `mydb`.`przesunięcia_magazynowe` (`pk`),
  CONSTRAINT `towary_towary_przesunięcia`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `mydb`.`towary` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`zamówienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zamówienia` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `fk_hurtownie` INT(10) NOT NULL,
  `fk_dostawcy` INT(10) NOT NULL,
  `fk_pracownicy` INT(11) NOT NULL,
  `data_zlecenia` TIMESTAMP NOT NULL,
  `data_odbioru` TIMESTAMP NOT NULL,
  `cena_sum_netto` DECIMAL(19,2) NOT NULL,
  `cena_sum_brutto` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `dostawcy_zamówienia` (`fk_dostawcy` ASC) VISIBLE,
  INDEX `hurtownie_zamówienia` (`fk_hurtownie` ASC) VISIBLE,
  INDEX `pracownicy_zamówienia` (`fk_pracownicy` ASC) VISIBLE,
  CONSTRAINT `dostawcy_zamówienia`
    FOREIGN KEY (`fk_dostawcy`)
    REFERENCES `mydb`.`dostawcy` (`pk`),
  CONSTRAINT `hurtownie_zamówienia`
    FOREIGN KEY (`fk_hurtownie`)
    REFERENCES `mydb`.`hurtownie` (`pk`),
  CONSTRAINT `pracownicy_zamówienia`
    FOREIGN KEY (`fk_pracownicy`)
    REFERENCES `mydb`.`pracownicy` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`zamówienia_sprzadaże`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zamówienia_sprzadaże` (
  `pk` INT(10) NOT NULL AUTO_INCREMENT,
  `fk_zamówienia` INT(10) NOT NULL,
  `fk_sprzedaże` INT(11) NOT NULL,
  `cena_jedn_netto` DECIMAL(19,2) NOT NULL,
  `cena_jedn_brutto` DECIMAL(19,2) NOT NULL,
  `ilość` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `sprzedaże_towary_sprzedaże` (`fk_sprzedaże` ASC) VISIBLE,
  INDEX `zamówienia_towary_sprzedaże` (`fk_zamówienia` ASC) VISIBLE,
  CONSTRAINT `sprzedaże_towary_sprzedaże`
    FOREIGN KEY (`fk_sprzedaże`)
    REFERENCES `mydb`.`sprzedaże` (`pk`),
  CONSTRAINT `zamówienia_towary_sprzedaże`
    FOREIGN KEY (`fk_zamówienia`)
    REFERENCES `mydb`.`zamówienia` (`pk`));


-- -----------------------------------------------------
-- Table `mydb`.`towary_sprzedaże`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`towary_sprzedaże` (
  `pk` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_towary` INT(10) NOT NULL,
  `fk_sprzedaże` INT(11) NOT NULL,
  `ilość` INT(11) NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `FKtowary_spr256522` (`fk_sprzedaże` ASC) VISIBLE,
  INDEX `towary_towary_sprzedaże` (`fk_towary` ASC) VISIBLE,
  CONSTRAINT `FKtowary_spr256522`
    FOREIGN KEY (`fk_sprzedaże`)
    REFERENCES `mydb`.`sprzedaże` (`pk`),
  CONSTRAINT `towary_towary_sprzedaże`
    FOREIGN KEY (`fk_towary`)
    REFERENCES `mydb`.`towary` (`pk`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
