
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (1,'STM32 microkontroler F401RD','STM32F401RD','High-performance access line,  ARM Cortex-M4 core with DSP and FPU,  384 Kbytes Flash,  84 MHz CPU,  ART Accelerator','true',50,61.5,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (2,'STM32 microkontroler F4071G','STM32F4071G','High-performance foundation line,  ARM Cortex-M4 core with DSP and FPU,  1 Mbyte Flash,  168 MHz CPU,  ART Accelerator,  Ethernet,  FSMC','true',60,73.8,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (3,'STM32 microkontroler F412VG','STM32F412VG','STM32 Dynamic Efficiency MCU with BAM,  High-performance and DSP with FPU,  ARM Cortex-M4 MCU with 1 Mbyte Flash,  100 MHz CPU,  Art Accelerator,  DFSDM','true',70,86.1,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (4,'STM32 microkontroler F412ZE','STM32F412ZE','STM32 Dynamic Efficiency MCU with BAM,  High-performance and DSP with FPU,  ARM Cortex-M4 MCU with 512 Kbytes Flash,  100 MHz CPU,  Art Accelerator,  DFSDM','true',80,98.4,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (5,'STM32 microkontroler F412ZG','STM32F412ZG','STM32 Dynamic Efficiency MCU with BAM,  High-performance and DSP with FPU,  ARM Cortex-M4 MCU with 1 Mbyte Flash,  100 MHz CPU,  Art Accelerator,  DFSDM','true',90,110.7,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (6,'sterownik silnika bezszczotkowego L6229','L6229','DMOS driver for three-phase brushless DC motor','true',55,67.65,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (7,'sterownik silnika bezszczotkowego L6234','L6234','Three phase motor driver','true',65,79.95,0.23,'true');
INSERT INTO towary(pk,nazwa,kod_producenta,opis,dostepnosc,cena_jedn_netto,cena_jedn_butto,stawka_vat,status) VALUES (8,'sterownik silnika bezszczotkowego L6235','L6235','DMOS driver for 3-phase brushless DC motor','true',75,92.25,0.23,'true');
