
INSERT INTO umowy(pk,rodzaj) VALUES (1,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (2,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (3,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (4,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (5,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (6,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (7,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (8,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (9,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (10,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (11,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (12,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (13,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (14,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (15,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (16,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (17,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (18,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (19,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (20,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (21,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (22,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (23,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (24,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (25,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (26,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (27,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (28,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (29,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (30,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (31,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (32,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (33,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (34,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (35,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (36,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (37,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (38,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (39,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (40,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (41,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (42,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (43,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (44,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (45,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (46,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (47,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (48,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (49,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (50,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (51,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (52,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (53,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (54,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (55,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (56,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (57,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (58,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (59,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (60,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (61,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (62,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (63,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (64,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (65,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (66,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (67,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (68,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (69,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (70,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (71,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (72,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (73,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (74,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (75,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (76,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (77,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (78,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (79,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (80,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (81,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (82,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (83,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (84,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (85,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (86,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (87,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (88,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (89,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (90,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (91,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (92,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (93,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (94,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (95,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (96,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (97,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (98,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (99,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (100,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (101,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (102,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (103,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (104,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (105,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (106,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (107,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (108,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (109,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (110,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (111,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (112,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (113,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (114,'umowa o pracę');
INSERT INTO umowy(pk,rodzaj) VALUES (115,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (116,'umowa zlecenia');
INSERT INTO umowy(pk,rodzaj) VALUES (117,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (118,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (119,'b2b');
INSERT INTO umowy(pk,rodzaj) VALUES (120,'umowa o pracę');
